drivers/pci/pcie/err.c: fix build error introduced by merge conflict
In ee118195e455 ("Merge branch 'v5.10/standard/base' into
v5.10/standard/nxp-sdk-5.10/nxp-soc") there was a conflict between
linux-stable backport de4534ac28c4 ("PCI/ERR: Rename reset_link() to
reset_subordinates()") and commit 7c27a63a0fa6 ("PCI/ERR: Fix reset logic in
pcie_do_recovery() call").

This introduced the following build failure:
drivers/pci/pcie/err.c: In function 'pcie_do_recovery':
drivers/pci/pcie/err.c:198:30: error: 'bus' undeclared (first use in this function)
  198 |                 pci_walk_bus(bus, report_frozen_detected, &status);
      |                              ^~~
drivers/pci/pcie/err.c:198:30: note: each undeclared identifier is reported only once for each function it appears in
drivers/pci/pcie/err.c:217:26: error: implicit declaration of function 'reset_link'; did you mean 'set_nlink'? [-Werror=implicit-function-declaration]
  217 |                 status = reset_link(dev);
      |                          ^~~~~~~~~~
      |                          set_nlink

Make the following adjustments to fix this:
  reset_link() -> reset_subordinates()
  pci_walk_bus(bus, ...) -> pci_walk_bridge(bridge, ...)

Signed-off-by: Ovidiu Panait <ovidiu.panait@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>