drivers: drm: vc4: fix build failure caused by merge conflicts
In 0487f95471af ("Merge branch 'v5.10/standard/base' into
v5.10/standard/bcm-2xxx-rpi") there was a conflict between linux-stable
backports
de63dbc29681 ("drm/vc4: hdmi: Disable audio if dmas property is present but empty")
717325e814d0 ("drm/vc4: hdmi: Limit the BCM2711 to the max without scrambling")
36f797a10f30 ("drm/vc4: hdmi: Fix timings for interlaced modes")
ed2f42bd8021 ("drm/vc4: dsi: Correct pixel order for DSI0")
and existing rpi SDK commits.

This caused the following build failures:
1. drivers/gpu/drm/vc4/vc4_crtc.c: In function 'vc4_crtc_config_pv':
drivers/gpu/drm/vc4/vc4_crtc.c:377:56:
warning: value computed is not used [-Wunused-value]
  377 |                              PV_VERTA_VBP) |
drivers/gpu/drm/vc4/vc4_crtc.c:380:57:
error: expected ';' before ')' token
  380 |                              PV_VERTA_VSYNC));
      |                                             ^
drivers/gpu/drm/vc4/vc4_crtc.c:380:57:
error: expected statement before ')' token

2. drivers/gpu/drm/vc4/vc4_hdmi.c:1540:13:
error: redeclaration of 'len' with no linkage
|  1540 |         int len;
|       |             ^~~

Remove unneeded duplicated code to fix this.

Signed-off-by: Ovidiu Panait <ovidiu.panait@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>