ACPI: thermal: remove unused tz_enabled fragment
This fix the following compile error:

drivers/acpi/thermal.c:1063:9: error: 'struct acpi_thermal' has no member named 'tz_enabled'
[11:19:48-0800]  1063 |  if (!tz->tz_enabled)
[11:19:48-0800]       |         ^~

The build error was imported by the backported upstream commit:
11084836e5fb ("ACPI: thermal: Do not call acpi_thermal_check() directly")
a wrong adjustment when apply this patch that import the deleted struct
member tz_enabled, remove it to make it the same with upstream to fix the
error.

Signed-off-by: Liwei Song <liwei.song@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>